server:
  error:
    include-stacktrace: on_param

spring:
  datasource:
    url: jdbc:h2:./taskManager
    username: sa
    password:

  jpa:
    show-sql: true

  h2:
    console:
      enabled: true
      path: /h2-console/
      settings:
        web-allow-others: true

  logging:
    level:
      root: INFO
      web: DEBUG

#springdoc:
#  swagger-ui:
#    path: /swagger.html