server:
  error:
    include-stacktrace: on_param

springdoc:
  swagger-ui:
    path: /swagger-ui.html

spring:
  datasource:
    username: "sa"
    password: ""
    url: jdbc:h2:./taskManager

  jpa:
    show-sql: true

  h2:
    console:
      enabled: true
      path: /h2-console/
      settings:
        web-allow-others: true

  logging:
    level:
      root: INFO
      web: DEBUG
