server:
  port: ${PORT:8090}

base-url: /api

spring:
  application:
    name: taskManager

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false

  mvc:
    hiddenmethod:
      filter:
        enabled: true

rollbar_token: 931a028efa194f95b7f9a91139bbd51b